name: OpenWRT Workflow

on:
  - push

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        branch: 
          - openwrt-23.05
        arch:
          # - aarch64_cortex-a53
          # - aarch64_cortex-a72
          # - aarch64_generic
          # - arm_arm1176jzf-s_vfp
          # - arm_arm926ej-s
          # - arm_cortex-a15_neon-vfpv4
          # - arm_cortex-a5_vfpv4
          # - arm_cortex-a7
          # - arm_cortex-a7_neon-vfpv4
          # - arm_cortex-a7_vfpv4
          # - arm_cortex-a8_vfpv3
          # - arm_cortex-a9
          # - arm_cortex-a9_neon
          # - arm_cortex-a9_vfpv3-d16
          # - arm_fa526
          # - arm_mpcore
          # - arm_xscale
          # - mips64_octeonplus
          # - mips_24kc
          # - mips_4kec
          # - mips_mips32
          # - mipsel_24kc
          # - mipsel_24kc_24kf
          # - mipsel_74kc
          # - mipsel_mips32
          # - ramips-mt76x8
          - x86_64
    container:
      image: openwrt/sdk:${{ matrix.arch }}-${{ matrix.branch }}
      options: --user root
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: 'openwrt'

      # - name: Prepare workflow
      #   shell: bash
      #   run: |
      #     sed -i 's/PKG_REV:=.*$/PKG_REV:=${{ github.sha }}/;s/PKG_VERSION:=.*$/PKG_VERSION:=$(date %Y%m%d)/' youtubeUnblock/Makefile
          
      - name: Build packages
        id: build
        working-directory: /builder
        shell: bash
        run: |
          echo "src-link youtubeUnblock $GITHUB_WORKSPACE" >> feeds.conf
          cat feeds.conf
          ./scripts/feeds update youtubeUnblock
          ./scripts/feeds install -a -p youtubeUnblock
          make defconfig
          make package/youtubeUnblock/compile V=s BUILD_LOG=1

      - name: Compress build logs
        if: always()
        env:
          ARCH: ${{ matrix.arch }}
        run: |
          tar -cJvf logs-$ARCH.tar.xz /builder/logs

      - name: Upload packages
        if: steps.build.outcome == 'success'
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.arch }}
          path: /builder/**/youtubeUnblock*.ipk
          if-no-files-found: error

      - name: Upload build logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: logs-${{ matrix.arch }}
          path: ./**/logs-*.tar.xz
